import { extractConfigFromTensorHistoryNode } from "./src/utils/config";
import { TensorHistoryNode } from "./src/dtProjects/types";

const mockNode: TensorHistoryNode = {
	lineage: 0,
	logical_time: 0,
	start_width: 512,
	start_height: 512,
	seed: 12345,
	steps: 20,
	guidance_scale: 7.5,
	strength: 1.0,
	model: "test_model",
	tensor_id: 1,
	mask_id: 0,
	wall_clock: 0,
	text_edits: 0,
	text_lineage: 0,
	batch_size: 1,
	sampler: 0,
	hires_fix: false,
	hires_fix_start_width: 0,
	hires_fix_start_height: 0,
	hires_fix_strength: 0,
	upscaler: undefined,
	scale_factor: 1,
	depth_map_id: 0,
	generated: true,
	image_guidance_scale: 1.0,
	seed_mode: 0,
	clip_skip: 1,
	controls: [],
	scribble_id: 0,
	pose_id: 0,
	loras: [],
	color_palette_id: 0,
	mask_blur: 0,
	custom_id: 0,
	face_restoration: undefined,
	clip_weight: 1.0,
	negative_prompt_for_image_prior: false,
	image_prior_steps: 0,
	data_stored: 0,
	preview_id: 0,
	content_offset_x: 0,
	content_offset_y: 0,
	scale_factor_by_120: 0,
	refiner_model: undefined,
	original_image_height: 0,
	original_image_width: 0,
	crop_top: 0,
	crop_left: 0,
	target_image_height: 0,
	target_image_width: 0,
	aesthetic_score: 0,
	negative_aesthetic_score: 0,
	zero_negative_prompt: false,
	refiner_start: 0,
	negative_original_image_height: 0,
	negative_original_image_width: 0,
	shuffle_data_stored: 0,
	fps_id: 0,
	motion_bucket_id: 0,
	cond_aug: 0,
	start_frame_cfg: 0,
	num_frames: 0,
	mask_blur_outset: 0,
	sharpness: 0,
	shift: 0,
	stage_2_steps: 0,
	stage_2_cfg: 0,
	stage_2_shift: 0,
	tiled_decoding: false,
	decoding_tile_width: 0,
	decoding_tile_height: 0,
	decoding_tile_overlap: 0,
	stochastic_sampling_gamma: 0,
	preserve_original_after_inpaint: false,
	tiled_diffusion: false,
	diffusion_tile_width: 0,
	diffusion_tile_height: 0,
	diffusion_tile_overlap: 0,
	upscaler_scale_factor: 0,
	script_session_id: 0,
	t5_text_encoder: false,
	separate_clip_l: false,
	clip_l_text: undefined,
	separate_open_clip_g: false,
	open_clip_g_text: undefined,
	speed_up_with_guidance_embed: false,
	guidance_embed: 0,
	resolution_dependent_shift: false,
	tea_cache_start: 0,
	tea_cache_end: 0,
	tea_cache_threshold: 0,
	tea_cache: false,
	separate_t5: false,
	t5_text: undefined,
	tea_cache_max_skip_steps: 0,
	text_prompt: undefined,
	negative_text_prompt: undefined,
	clip_id: 0,
	index_in_a_clip: 0,
	causal_inference_enabled: false,
	causal_inference: 0,
	causal_inference_pad: 0,
	cfg_zero_star: false,
	cfg_zero_init_steps: 0,
	generation_time: 0,
	reason: 0,
};

const config = extractConfigFromTensorHistoryNode(mockNode);

console.log("Config extracted successfully:", config);

if (config.width !== 512 || config.height !== 512 || config.seed !== 12345) {
	console.error("Verification failed: Incorrect values mapped.");
	process.exit(1);
}

if (config.model !== "test_model") {
	console.error("Verification failed: Model not mapped correctly.");
	process.exit(1);
}
