//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "cnets")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub cnet_id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub filename: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::image_cnets::Entity")]
    ImageCnets,
}

impl Related<super::image_cnets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageCnets.def()
    }
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        super::image_cnets::Relation::Images.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::image_cnets::Relation::Cnets.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
