//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "image_loras")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub lora_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::images::Entity",
        from = "Column::ImageId",
        to = "super::images::Column::ImageId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Images,
    #[sea_orm(
        belongs_to = "super::loras::Entity",
        from = "Column::LoraId",
        to = "super::loras::Column::LoraId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Loras,
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Images.def()
    }
}

impl Related<super::loras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Loras.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
