//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub project_id: i32,
    pub model_id: Option<i32>,
    pub refiner_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prompt: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub negative_prompt: Option<String>,
    pub node_id: i64,
    pub preview_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::image_cnets::Entity")]
    ImageCnets,
    #[sea_orm(has_many = "super::image_loras::Entity")]
    ImageLoras,
    #[sea_orm(
        belongs_to = "super::models::Entity",
        from = "Column::RefinerId",
        to = "super::models::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Models2,
    #[sea_orm(
        belongs_to = "super::models::Entity",
        from = "Column::ModelId",
        to = "super::models::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Models1,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
}

impl Related<super::image_cnets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageCnets.def()
    }
}

impl Related<super::image_loras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageLoras.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
