//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "image_controls")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub control_id: i32,
    #[sea_orm(column_type = "Float")]
    pub weight: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::images::Entity",
        from = "Column::ImageId",
        to = "super::images::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Images,
    #[sea_orm(
        belongs_to = "super::models::Entity",
        from = "Column::ControlId",
        to = "super::models::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Models,
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Images.def()
    }
}

impl Related<super::models::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Models.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
