//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::enums::Sampler;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub project_id: i64,
    pub node_id: i64,
    pub preview_id: i64,
    pub clip_id: i64,
    pub wall_clock: DateTimeUtc,
    pub model_id: Option<i64>,
    pub refiner_id: Option<i64>,
    #[sea_orm(column_type = "Float", nullable)]
    pub refiner_start: Option<f32>,
    pub upscaler_id: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub prompt: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub negative_prompt: Option<String>,
    pub start_width: i16,
    pub start_height: i16,
    pub seed: i64,
    #[sea_orm(column_type = "Float")]
    pub strength: f32,
    pub steps: i16,
    #[sea_orm(column_type = "Float")]
    pub guidance_scale: f32,
    #[sea_orm(column_type = "Float")]
    pub shift: f32,
    #[sea_orm(num_enum)]
    pub sampler: Sampler,
    pub hires_fix: bool,
    pub tiled_decoding: bool,
    pub tiled_diffusion: bool,
    pub tea_cache: bool,
    pub cfg_zero_star: bool,
    pub has_mask: bool,
    pub has_depth: bool,
    pub has_pose: bool,
    pub has_color: bool,
    pub has_custom: bool,
    pub has_scribble: bool,
    pub has_shuffle: bool,
    
    #[sea_orm(has_many)]
    pub image_controls: HasMany<super::image_controls::Entity>,

    #[sea_orm(has_many)]
    pub image_loras: HasMany<super::image_loras::Entity>,

    #[sea_orm(
        belongs_to,
        relation_enum = "Upscalers",
        from = "upscaler_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub upscaler: HasOne<super::models::Entity>,

    #[sea_orm(
        belongs_to,
        relation_enum = "Refiners",
        from = "refiner_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub refiner: HasOne<super::models::Entity>,

    #[sea_orm(
        belongs_to,
        relation_enum = "Models",
        from = "model_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub model: HasOne<super::models::Entity>,

    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub project: HasOne<super::projects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
