//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "image_controls")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub image_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub control_id: i64,
    #[sea_orm(column_type = "Float")]
    pub weight: f32,
    #[sea_orm(
        belongs_to,
        from = "image_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub images: HasOne<super::images::Entity>,
    #[sea_orm(
        belongs_to,
        from = "control_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub control_model: HasOne<super::models::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
