//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::enums::ModelType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "models")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub model_type: ModelType,
    pub filename: String,
    pub name: Option<String>,
    pub version: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::image_controls::Entity")]
    ImageControls,
    #[sea_orm(has_many = "super::image_loras::Entity")]
    ImageLoras,
}

impl Related<super::image_controls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageControls.def()
    }
}

impl Related<super::image_loras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageLoras.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
