//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "models")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,

    #[sea_orm(num_enum)]
    pub model_type: ModelType,

    pub filename: String,
    pub name: Option<String>,
    pub version: Option<String>,
}

/// Model type enum stored as i8
#[derive(Copy, Clone, Debug, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "i8", db_type = "TinyInteger")]
pub enum ModelType {
    #[sea_orm(num_value = 0)]
    None,
    #[sea_orm(num_value = 1)]
    Model,
    #[sea_orm(num_value = 2)]
    Lora,
    #[sea_orm(num_value = 3)]
    Cnet,
    #[sea_orm(num_value = 4)]
    Upscaler,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::image_controls::Entity")]
    ImageControls,
    #[sea_orm(has_many = "super::image_loras::Entity")]
    ImageLoras,
}

impl Related<super::image_controls::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageControls.def()
    }
}

impl Related<super::image_loras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageLoras.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
