//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "watch_folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub path: String,
    pub bookmark: String,
    pub recursive: Option<bool>,
    pub last_updated: Option<i64>,
    #[sea_orm(has_many)]
    pub projects: HasMany<super::projects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
