//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.19

use crate::enums::ItemType;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "watch_folders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub path: String,
    pub recursive: Option<bool>,
    #[sea_orm(num_enum)]
    pub item_type: ItemType,
}

impl ActiveModelBehavior for ActiveModel {}
