//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "dictitem_v_dflat_internal__")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub rowid: Option<i32>,
    #[sea_orm(column_name = "__pk0", column_type = "Text", nullable)]
    pub pk0: Option<String>,
    #[sea_orm(column_name = "__pk1", column_type = "Text", nullable)]
    pub pk1: Option<String>,
    #[sea_orm(column_type = "Blob", nullable)]
    pub p: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
