//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "tensors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub name: Option<String>,
    pub r#type: Option<i32>,
    pub format: Option<i32>,
    pub datatype: Option<i32>,
    #[sea_orm(column_type = "Blob", nullable)]
    pub dim: Option<Vec<u8>>,
    #[sea_orm(column_type = "Blob", nullable)]
    pub data: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
