import { DrawThingsMetaData } from "@/types"
import { TensorHistoryNode } from "@/dtProjects/types"

export function extractConfigFromTensorHistoryNode(
	node: TensorHistoryNode,
): DrawThingsMetaData["config"] {
	return {
		aestheticScore: node.aesthetic_score,
		batchCount: 1, // Defaulting to 1 as it's not in TensorHistoryNode
		batchSize: node.batch_size,
		causalInference: node.causal_inference,
		causalInferencePad: node.causal_inference_pad,
		cfgZeroInitSteps: node.cfg_zero_init_steps,
		cfgZeroStar: node.cfg_zero_star,
		clipLText: node.clip_l_text ?? "",
		clipSkip: node.clip_skip,
		clipWeight: node.clip_weight,
		controls: node.controls ?? [],
		cropLeft: node.crop_left,
		cropTop: node.crop_top,
		decodingTileHeight: node.decoding_tile_height,
		decodingTileOverlap: node.decoding_tile_overlap,
		decodingTileWidth: node.decoding_tile_width,
		diffusionTileHeight: node.diffusion_tile_height,
		diffusionTileOverlap: node.diffusion_tile_overlap,
		diffusionTileWidth: node.diffusion_tile_width,
		fps: node.fps_id, // Assuming fps_id maps to fps
		guidanceEmbed: node.guidance_embed,
		guidanceScale: node.guidance_scale,
		guidingFrameNoise: 0, // Not found in TensorHistoryNode
		height: node.start_height,
		hiresFix: node.hires_fix,
		hiresFixHeight: node.hires_fix_start_height,
		hiresFixStrength: node.hires_fix_strength,
		hiresFixWidth: node.hires_fix_start_width,
		id: node.tensor_id,
		imageGuidanceScale: node.image_guidance_scale,
		imagePriorSteps: node.image_prior_steps,
		loras: (node.loras as any) ?? [], // Casting to any to avoid type mismatch with ObjectConstructor[][]
		maskBlur: node.mask_blur,
		maskBlurOutset: node.mask_blur_outset,
		model: node.model ?? "",
		motionScale: 0, // Not found in TensorHistoryNode
		negativeAestheticScore: node.negative_aesthetic_score,
		negativeOriginalImageHeight: node.negative_original_image_height,
		negativeOriginalImageWidth: node.negative_original_image_width,
		negativePromptForImagePrior: node.negative_prompt_for_image_prior,
		numFrames: node.num_frames,
		originalImageHeight: node.original_image_height,
		originalImageWidth: node.original_image_width,
		preserveOriginalAfterInpaint: node.preserve_original_after_inpaint,
		refinerStart: node.refiner_start,
		resolutionDependentShift: node.resolution_dependent_shift,
		sampler: node.sampler,
		seed: node.seed,
		seedMode: node.seed_mode,
		separateClipL: node.separate_clip_l,
		separateOpenClipG: node.separate_open_clip_g,
		separateT5: node.separate_t5,
		sharpness: node.sharpness,
		shift: node.shift,
		speedUpWithGuidanceEmbed: node.speed_up_with_guidance_embed,
		stage2Guidance: 0, // Not found in TensorHistoryNode
		stage2Shift: node.stage_2_shift,
		stage2Steps: node.stage_2_steps,
		startFrameGuidance: node.start_frame_cfg,
		steps: node.steps,
		stochasticSamplingGamma: node.stochastic_sampling_gamma,
		strength: node.strength,
		t5TextEncoder: node.t5_text_encoder,
		targetImageHeight: node.target_image_height,
		targetImageWidth: node.target_image_width,
		teaCache: node.tea_cache,
		teaCacheEnd: node.tea_cache_end,
		teaCacheMaxSkipSteps: node.tea_cache_max_skip_steps,
		teaCacheStart: node.tea_cache_start,
		teaCacheThreshold: node.tea_cache_threshold,
		tiledDecoding: node.tiled_decoding,
		tiledDiffusion: node.tiled_diffusion,
		upscalerScaleFactor: node.upscaler_scale_factor,
		width: node.start_width,
		zeroNegativePrompt: node.zero_negative_prompt,
	}
}