// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum ClipOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Clip<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Clip<'a> {
  type Inner = Clip<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Clip<'a> {
  pub const VT_CLIP_ID: flatbuffers::VOffsetT = 4;
  pub const VT_COUNT: flatbuffers::VOffsetT = 6;
  pub const VT_FRAMES_PER_SECOND: flatbuffers::VOffsetT = 8;
  pub const VT_WIDTH: flatbuffers::VOffsetT = 10;
  pub const VT_HEIGHT: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Clip { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ClipArgs
  ) -> flatbuffers::WIPOffset<Clip<'bldr>> {
    let mut builder = ClipBuilder::new(_fbb);
    builder.add_frames_per_second(args.frames_per_second);
    builder.add_clip_id(args.clip_id);
    builder.add_height(args.height);
    builder.add_width(args.width);
    builder.add_count(args.count);
    builder.finish()
  }


  #[inline]
  pub fn clip_id(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Clip::VT_CLIP_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn count(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Clip::VT_COUNT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn frames_per_second(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Clip::VT_FRAMES_PER_SECOND, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn width(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Clip::VT_WIDTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn height(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(Clip::VT_HEIGHT, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Clip<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("clip_id", Self::VT_CLIP_ID, false)?
     .visit_field::<i32>("count", Self::VT_COUNT, false)?
     .visit_field::<f64>("frames_per_second", Self::VT_FRAMES_PER_SECOND, false)?
     .visit_field::<i32>("width", Self::VT_WIDTH, false)?
     .visit_field::<i32>("height", Self::VT_HEIGHT, false)?
     .finish();
    Ok(())
  }
}
pub struct ClipArgs {
    pub clip_id: i64,
    pub count: i32,
    pub frames_per_second: f64,
    pub width: i32,
    pub height: i32,
}
impl<'a> Default for ClipArgs {
  #[inline]
  fn default() -> Self {
    ClipArgs {
      clip_id: 0,
      count: 0,
      frames_per_second: 0.0,
      width: 0,
      height: 0,
    }
  }
}

pub struct ClipBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ClipBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_clip_id(&mut self, clip_id: i64) {
    self.fbb_.push_slot::<i64>(Clip::VT_CLIP_ID, clip_id, 0);
  }
  #[inline]
  pub fn add_count(&mut self, count: i32) {
    self.fbb_.push_slot::<i32>(Clip::VT_COUNT, count, 0);
  }
  #[inline]
  pub fn add_frames_per_second(&mut self, frames_per_second: f64) {
    self.fbb_.push_slot::<f64>(Clip::VT_FRAMES_PER_SECOND, frames_per_second, 0.0);
  }
  #[inline]
  pub fn add_width(&mut self, width: i32) {
    self.fbb_.push_slot::<i32>(Clip::VT_WIDTH, width, 0);
  }
  #[inline]
  pub fn add_height(&mut self, height: i32) {
    self.fbb_.push_slot::<i32>(Clip::VT_HEIGHT, height, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ClipBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ClipBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Clip<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Clip<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Clip");
      ds.field("clip_id", &self.clip_id());
      ds.field("count", &self.count());
      ds.field("frames_per_second", &self.frames_per_second());
      ds.field("width", &self.width());
      ds.field("height", &self.height());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Clip`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clip_unchecked`.
pub fn root_as_clip(buf: &[u8]) -> Result<Clip, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Clip>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Clip` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_clip_unchecked`.
pub fn size_prefixed_root_as_clip(buf: &[u8]) -> Result<Clip, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Clip>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Clip` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clip_unchecked`.
pub fn root_as_clip_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Clip<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Clip<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Clip` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clip_unchecked`.
pub fn size_prefixed_root_as_clip_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Clip<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Clip<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Clip and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Clip`.
pub unsafe fn root_as_clip_unchecked(buf: &[u8]) -> Clip {
  unsafe { flatbuffers::root_unchecked::<Clip>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Clip and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Clip`.
pub unsafe fn size_prefixed_root_as_clip_unchecked(buf: &[u8]) -> Clip {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Clip>(buf) }
}
#[inline]
pub fn finish_clip_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Clip<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_clip_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Clip<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
