// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_CONTROL_INPUT_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_CONTROL_INPUT_TYPE: i8 = 18;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_CONTROL_INPUT_TYPE: [ControlInputType; 19] = [
  ControlInputType::Unspecified,
  ControlInputType::Custom,
  ControlInputType::Depth,
  ControlInputType::Canny,
  ControlInputType::Scribble,
  ControlInputType::Pose,
  ControlInputType::Normalbae,
  ControlInputType::Color,
  ControlInputType::Lineart,
  ControlInputType::Softedge,
  ControlInputType::Seg,
  ControlInputType::Inpaint,
  ControlInputType::Ip2p,
  ControlInputType::Shuffle,
  ControlInputType::Mlsd,
  ControlInputType::Tile,
  ControlInputType::Blur,
  ControlInputType::Lowquality,
  ControlInputType::Gray,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ControlInputType(pub i8);
#[allow(non_upper_case_globals)]
impl ControlInputType {
  pub const Unspecified: Self = Self(0);
  pub const Custom: Self = Self(1);
  pub const Depth: Self = Self(2);
  pub const Canny: Self = Self(3);
  pub const Scribble: Self = Self(4);
  pub const Pose: Self = Self(5);
  pub const Normalbae: Self = Self(6);
  pub const Color: Self = Self(7);
  pub const Lineart: Self = Self(8);
  pub const Softedge: Self = Self(9);
  pub const Seg: Self = Self(10);
  pub const Inpaint: Self = Self(11);
  pub const Ip2p: Self = Self(12);
  pub const Shuffle: Self = Self(13);
  pub const Mlsd: Self = Self(14);
  pub const Tile: Self = Self(15);
  pub const Blur: Self = Self(16);
  pub const Lowquality: Self = Self(17);
  pub const Gray: Self = Self(18);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 18;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Unspecified,
    Self::Custom,
    Self::Depth,
    Self::Canny,
    Self::Scribble,
    Self::Pose,
    Self::Normalbae,
    Self::Color,
    Self::Lineart,
    Self::Softedge,
    Self::Seg,
    Self::Inpaint,
    Self::Ip2p,
    Self::Shuffle,
    Self::Mlsd,
    Self::Tile,
    Self::Blur,
    Self::Lowquality,
    Self::Gray,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Unspecified => Some("Unspecified"),
      Self::Custom => Some("Custom"),
      Self::Depth => Some("Depth"),
      Self::Canny => Some("Canny"),
      Self::Scribble => Some("Scribble"),
      Self::Pose => Some("Pose"),
      Self::Normalbae => Some("Normalbae"),
      Self::Color => Some("Color"),
      Self::Lineart => Some("Lineart"),
      Self::Softedge => Some("Softedge"),
      Self::Seg => Some("Seg"),
      Self::Inpaint => Some("Inpaint"),
      Self::Ip2p => Some("Ip2p"),
      Self::Shuffle => Some("Shuffle"),
      Self::Mlsd => Some("Mlsd"),
      Self::Tile => Some("Tile"),
      Self::Blur => Some("Blur"),
      Self::Lowquality => Some("Lowquality"),
      Self::Gray => Some("Gray"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ControlInputType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for ControlInputType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for ControlInputType {
    type Output = ControlInputType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<i8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for ControlInputType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ControlInputType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ControlInputType {}
