// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum LoRAOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LoRA<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for LoRA<'a> {
  type Inner = LoRA<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> LoRA<'a> {
  pub const VT_FILE: flatbuffers::VOffsetT = 4;
  pub const VT_WEIGHT: flatbuffers::VOffsetT = 6;
  pub const VT_MODE: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    LoRA { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LoRAArgs<'args>
  ) -> flatbuffers::WIPOffset<LoRA<'bldr>> {
    let mut builder = LoRABuilder::new(_fbb);
    builder.add_weight(args.weight);
    if let Some(x) = args.file { builder.add_file(x); }
    builder.add_mode(args.mode);
    builder.finish()
  }


  #[inline]
  pub fn file(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(LoRA::VT_FILE, None)}
  }
  #[inline]
  pub fn weight(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(LoRA::VT_WEIGHT, Some(0.6)).unwrap()}
  }
  #[inline]
  pub fn mode(&self) -> LoRAMode {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<LoRAMode>(LoRA::VT_MODE, Some(LoRAMode::All)).unwrap()}
  }
}

impl flatbuffers::Verifiable for LoRA<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("file", Self::VT_FILE, false)?
     .visit_field::<f32>("weight", Self::VT_WEIGHT, false)?
     .visit_field::<LoRAMode>("mode", Self::VT_MODE, false)?
     .finish();
    Ok(())
  }
}
pub struct LoRAArgs<'a> {
    pub file: Option<flatbuffers::WIPOffset<&'a str>>,
    pub weight: f32,
    pub mode: LoRAMode,
}
impl<'a> Default for LoRAArgs<'a> {
  #[inline]
  fn default() -> Self {
    LoRAArgs {
      file: None,
      weight: 0.6,
      mode: LoRAMode::All,
    }
  }
}

pub struct LoRABuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LoRABuilder<'a, 'b, A> {
  #[inline]
  pub fn add_file(&mut self, file: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LoRA::VT_FILE, file);
  }
  #[inline]
  pub fn add_weight(&mut self, weight: f32) {
    self.fbb_.push_slot::<f32>(LoRA::VT_WEIGHT, weight, 0.6);
  }
  #[inline]
  pub fn add_mode(&mut self, mode: LoRAMode) {
    self.fbb_.push_slot::<LoRAMode>(LoRA::VT_MODE, mode, LoRAMode::All);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LoRABuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LoRABuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<LoRA<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for LoRA<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("LoRA");
      ds.field("file", &self.file());
      ds.field("weight", &self.weight());
      ds.field("mode", &self.mode());
      ds.finish()
  }
}
