#![allow(dead_code)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(mismatched_lifetime_syntaxes)]

// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
mod text_type_generated;
pub use self::text_type_generated::*;
mod text_range_generated;
pub use self::text_range_generated::*;
mod text_modification_generated;
pub use self::text_modification_generated::*;
mod text_history_node_generated;
pub use self::text_history_node_generated::*;
