// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_SAMPLER_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_SAMPLER_TYPE: i8 = 18;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_SAMPLER_TYPE: [SamplerType; 19] = [
  SamplerType::DPMPP2MKarras,
  SamplerType::EulerA,
  SamplerType::DDIM,
  SamplerType::PLMS,
  SamplerType::DPMPPSDEKarras,
  SamplerType::UniPC,
  SamplerType::LCM,
  SamplerType::EulerASubstep,
  SamplerType::DPMPPSDESubstep,
  SamplerType::TCD,
  SamplerType::EulerATrailing,
  SamplerType::DPMPPSDETrailing,
  SamplerType::DPMPP2MAYS,
  SamplerType::EulerAAYS,
  SamplerType::DPMPPSDEAYS,
  SamplerType::DPMPP2MTrailing,
  SamplerType::DDIMTrailing,
  SamplerType::UniPCTrailing,
  SamplerType::UniPCAYS,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct SamplerType(pub i8);
#[allow(non_upper_case_globals)]
impl SamplerType {
  pub const DPMPP2MKarras: Self = Self(0);
  pub const EulerA: Self = Self(1);
  pub const DDIM: Self = Self(2);
  pub const PLMS: Self = Self(3);
  pub const DPMPPSDEKarras: Self = Self(4);
  pub const UniPC: Self = Self(5);
  pub const LCM: Self = Self(6);
  pub const EulerASubstep: Self = Self(7);
  pub const DPMPPSDESubstep: Self = Self(8);
  pub const TCD: Self = Self(9);
  pub const EulerATrailing: Self = Self(10);
  pub const DPMPPSDETrailing: Self = Self(11);
  pub const DPMPP2MAYS: Self = Self(12);
  pub const EulerAAYS: Self = Self(13);
  pub const DPMPPSDEAYS: Self = Self(14);
  pub const DPMPP2MTrailing: Self = Self(15);
  pub const DDIMTrailing: Self = Self(16);
  pub const UniPCTrailing: Self = Self(17);
  pub const UniPCAYS: Self = Self(18);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 18;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::DPMPP2MKarras,
    Self::EulerA,
    Self::DDIM,
    Self::PLMS,
    Self::DPMPPSDEKarras,
    Self::UniPC,
    Self::LCM,
    Self::EulerASubstep,
    Self::DPMPPSDESubstep,
    Self::TCD,
    Self::EulerATrailing,
    Self::DPMPPSDETrailing,
    Self::DPMPP2MAYS,
    Self::EulerAAYS,
    Self::DPMPPSDEAYS,
    Self::DPMPP2MTrailing,
    Self::DDIMTrailing,
    Self::UniPCTrailing,
    Self::UniPCAYS,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::DPMPP2MKarras => Some("DPMPP2MKarras"),
      Self::EulerA => Some("EulerA"),
      Self::DDIM => Some("DDIM"),
      Self::PLMS => Some("PLMS"),
      Self::DPMPPSDEKarras => Some("DPMPPSDEKarras"),
      Self::UniPC => Some("UniPC"),
      Self::LCM => Some("LCM"),
      Self::EulerASubstep => Some("EulerASubstep"),
      Self::DPMPPSDESubstep => Some("DPMPPSDESubstep"),
      Self::TCD => Some("TCD"),
      Self::EulerATrailing => Some("EulerATrailing"),
      Self::DPMPPSDETrailing => Some("DPMPPSDETrailing"),
      Self::DPMPP2MAYS => Some("DPMPP2MAYS"),
      Self::EulerAAYS => Some("EulerAAYS"),
      Self::DPMPPSDEAYS => Some("DPMPPSDEAYS"),
      Self::DPMPP2MTrailing => Some("DPMPP2MTrailing"),
      Self::DDIMTrailing => Some("DDIMTrailing"),
      Self::UniPCTrailing => Some("UniPCTrailing"),
      Self::UniPCAYS => Some("UniPCAYS"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for SamplerType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for SamplerType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for SamplerType {
    type Output = SamplerType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<i8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for SamplerType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for SamplerType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for SamplerType {}
