// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum TensorMoodboardDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TensorMoodboardData<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TensorMoodboardData<'a> {
  type Inner = TensorMoodboardData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TensorMoodboardData<'a> {
  pub const VT_LINEAGE: flatbuffers::VOffsetT = 4;
  pub const VT_LOGICAL_TIME: flatbuffers::VOffsetT = 6;
  pub const VT_INDEX: flatbuffers::VOffsetT = 8;
  pub const VT_SHUFFLE_ID: flatbuffers::VOffsetT = 10;
  pub const VT_WEIGHT: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TensorMoodboardData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TensorMoodboardDataArgs
  ) -> flatbuffers::WIPOffset<TensorMoodboardData<'bldr>> {
    let mut builder = TensorMoodboardDataBuilder::new(_fbb);
    builder.add_shuffle_id(args.shuffle_id);
    builder.add_index(args.index);
    builder.add_logical_time(args.logical_time);
    builder.add_lineage(args.lineage);
    builder.add_weight(args.weight);
    builder.finish()
  }


  #[inline]
  pub fn lineage(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(TensorMoodboardData::VT_LINEAGE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn logical_time(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(TensorMoodboardData::VT_LOGICAL_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn index(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(TensorMoodboardData::VT_INDEX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn shuffle_id(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(TensorMoodboardData::VT_SHUFFLE_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn weight(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(TensorMoodboardData::VT_WEIGHT, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for TensorMoodboardData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("lineage", Self::VT_LINEAGE, false)?
     .visit_field::<i64>("logical_time", Self::VT_LOGICAL_TIME, false)?
     .visit_field::<i64>("index", Self::VT_INDEX, false)?
     .visit_field::<i64>("shuffle_id", Self::VT_SHUFFLE_ID, false)?
     .visit_field::<f32>("weight", Self::VT_WEIGHT, false)?
     .finish();
    Ok(())
  }
}
pub struct TensorMoodboardDataArgs {
    pub lineage: i64,
    pub logical_time: i64,
    pub index: i64,
    pub shuffle_id: i64,
    pub weight: f32,
}
impl<'a> Default for TensorMoodboardDataArgs {
  #[inline]
  fn default() -> Self {
    TensorMoodboardDataArgs {
      lineage: 0,
      logical_time: 0,
      index: 0,
      shuffle_id: 0,
      weight: 0.0,
    }
  }
}

pub struct TensorMoodboardDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TensorMoodboardDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_lineage(&mut self, lineage: i64) {
    self.fbb_.push_slot::<i64>(TensorMoodboardData::VT_LINEAGE, lineage, 0);
  }
  #[inline]
  pub fn add_logical_time(&mut self, logical_time: i64) {
    self.fbb_.push_slot::<i64>(TensorMoodboardData::VT_LOGICAL_TIME, logical_time, 0);
  }
  #[inline]
  pub fn add_index(&mut self, index: i64) {
    self.fbb_.push_slot::<i64>(TensorMoodboardData::VT_INDEX, index, 0);
  }
  #[inline]
  pub fn add_shuffle_id(&mut self, shuffle_id: i64) {
    self.fbb_.push_slot::<i64>(TensorMoodboardData::VT_SHUFFLE_ID, shuffle_id, 0);
  }
  #[inline]
  pub fn add_weight(&mut self, weight: f32) {
    self.fbb_.push_slot::<f32>(TensorMoodboardData::VT_WEIGHT, weight, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TensorMoodboardDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TensorMoodboardDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TensorMoodboardData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TensorMoodboardData<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TensorMoodboardData");
      ds.field("lineage", &self.lineage());
      ds.field("logical_time", &self.logical_time());
      ds.field("index", &self.index());
      ds.field("shuffle_id", &self.shuffle_id());
      ds.field("weight", &self.weight());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `TensorMoodboardData`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tensor_moodboard_data_unchecked`.
pub fn root_as_tensor_moodboard_data(buf: &[u8]) -> Result<TensorMoodboardData, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<TensorMoodboardData>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `TensorMoodboardData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_tensor_moodboard_data_unchecked`.
pub fn size_prefixed_root_as_tensor_moodboard_data(buf: &[u8]) -> Result<TensorMoodboardData, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<TensorMoodboardData>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `TensorMoodboardData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tensor_moodboard_data_unchecked`.
pub fn root_as_tensor_moodboard_data_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TensorMoodboardData<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<TensorMoodboardData<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `TensorMoodboardData` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tensor_moodboard_data_unchecked`.
pub fn size_prefixed_root_as_tensor_moodboard_data_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TensorMoodboardData<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<TensorMoodboardData<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a TensorMoodboardData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `TensorMoodboardData`.
pub unsafe fn root_as_tensor_moodboard_data_unchecked(buf: &[u8]) -> TensorMoodboardData {
  unsafe { flatbuffers::root_unchecked::<TensorMoodboardData>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed TensorMoodboardData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `TensorMoodboardData`.
pub unsafe fn size_prefixed_root_as_tensor_moodboard_data_unchecked(buf: &[u8]) -> TensorMoodboardData {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<TensorMoodboardData>(buf) }
}
#[inline]
pub fn finish_tensor_moodboard_data_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<TensorMoodboardData<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_tensor_moodboard_data_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<TensorMoodboardData<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
