// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum TextHistoryNodeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TextHistoryNode<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TextHistoryNode<'a> {
  type Inner = TextHistoryNode<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TextHistoryNode<'a> {
  pub const VT_LINEAGE: flatbuffers::VOffsetT = 4;
  pub const VT_LOGICAL_TIME: flatbuffers::VOffsetT = 6;
  pub const VT_START_EDITS: flatbuffers::VOffsetT = 8;
  pub const VT_START_POSITIVE_TEXT: flatbuffers::VOffsetT = 10;
  pub const VT_START_NEGATIVE_TEXT: flatbuffers::VOffsetT = 12;
  pub const VT_MODIFICATIONS: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TextHistoryNode { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TextHistoryNodeArgs<'args>
  ) -> flatbuffers::WIPOffset<TextHistoryNode<'bldr>> {
    let mut builder = TextHistoryNodeBuilder::new(_fbb);
    builder.add_start_edits(args.start_edits);
    builder.add_logical_time(args.logical_time);
    builder.add_lineage(args.lineage);
    if let Some(x) = args.modifications { builder.add_modifications(x); }
    if let Some(x) = args.start_negative_text { builder.add_start_negative_text(x); }
    if let Some(x) = args.start_positive_text { builder.add_start_positive_text(x); }
    builder.finish()
  }


  #[inline]
  pub fn lineage(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(TextHistoryNode::VT_LINEAGE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn logical_time(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(TextHistoryNode::VT_LOGICAL_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn start_edits(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(TextHistoryNode::VT_START_EDITS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn start_positive_text(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TextHistoryNode::VT_START_POSITIVE_TEXT, None)}
  }
  #[inline]
  pub fn start_negative_text(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TextHistoryNode::VT_START_NEGATIVE_TEXT, None)}
  }
  #[inline]
  pub fn modifications(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TextModification<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TextModification>>>>(TextHistoryNode::VT_MODIFICATIONS, None)}
  }
}

impl flatbuffers::Verifiable for TextHistoryNode<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("lineage", Self::VT_LINEAGE, false)?
     .visit_field::<i64>("logical_time", Self::VT_LOGICAL_TIME, false)?
     .visit_field::<i64>("start_edits", Self::VT_START_EDITS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("start_positive_text", Self::VT_START_POSITIVE_TEXT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("start_negative_text", Self::VT_START_NEGATIVE_TEXT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<TextModification>>>>("modifications", Self::VT_MODIFICATIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct TextHistoryNodeArgs<'a> {
    pub lineage: i64,
    pub logical_time: i64,
    pub start_edits: i64,
    pub start_positive_text: Option<flatbuffers::WIPOffset<&'a str>>,
    pub start_negative_text: Option<flatbuffers::WIPOffset<&'a str>>,
    pub modifications: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TextModification<'a>>>>>,
}
impl<'a> Default for TextHistoryNodeArgs<'a> {
  #[inline]
  fn default() -> Self {
    TextHistoryNodeArgs {
      lineage: 0,
      logical_time: 0,
      start_edits: 0,
      start_positive_text: None,
      start_negative_text: None,
      modifications: None,
    }
  }
}

pub struct TextHistoryNodeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TextHistoryNodeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_lineage(&mut self, lineage: i64) {
    self.fbb_.push_slot::<i64>(TextHistoryNode::VT_LINEAGE, lineage, 0);
  }
  #[inline]
  pub fn add_logical_time(&mut self, logical_time: i64) {
    self.fbb_.push_slot::<i64>(TextHistoryNode::VT_LOGICAL_TIME, logical_time, 0);
  }
  #[inline]
  pub fn add_start_edits(&mut self, start_edits: i64) {
    self.fbb_.push_slot::<i64>(TextHistoryNode::VT_START_EDITS, start_edits, 0);
  }
  #[inline]
  pub fn add_start_positive_text(&mut self, start_positive_text: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TextHistoryNode::VT_START_POSITIVE_TEXT, start_positive_text);
  }
  #[inline]
  pub fn add_start_negative_text(&mut self, start_negative_text: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TextHistoryNode::VT_START_NEGATIVE_TEXT, start_negative_text);
  }
  #[inline]
  pub fn add_modifications(&mut self, modifications: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<TextModification<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TextHistoryNode::VT_MODIFICATIONS, modifications);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TextHistoryNodeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TextHistoryNodeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TextHistoryNode<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TextHistoryNode<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TextHistoryNode");
      ds.field("lineage", &self.lineage());
      ds.field("logical_time", &self.logical_time());
      ds.field("start_edits", &self.start_edits());
      ds.field("start_positive_text", &self.start_positive_text());
      ds.field("start_negative_text", &self.start_negative_text());
      ds.field("modifications", &self.modifications());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `TextHistoryNode`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_text_history_node_unchecked`.
pub fn root_as_text_history_node(buf: &[u8]) -> Result<TextHistoryNode, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<TextHistoryNode>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `TextHistoryNode` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_text_history_node_unchecked`.
pub fn size_prefixed_root_as_text_history_node(buf: &[u8]) -> Result<TextHistoryNode, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<TextHistoryNode>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `TextHistoryNode` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_text_history_node_unchecked`.
pub fn root_as_text_history_node_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TextHistoryNode<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<TextHistoryNode<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `TextHistoryNode` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_text_history_node_unchecked`.
pub fn size_prefixed_root_as_text_history_node_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TextHistoryNode<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<TextHistoryNode<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a TextHistoryNode and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `TextHistoryNode`.
pub unsafe fn root_as_text_history_node_unchecked(buf: &[u8]) -> TextHistoryNode {
  unsafe { flatbuffers::root_unchecked::<TextHistoryNode>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed TextHistoryNode and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `TextHistoryNode`.
pub unsafe fn size_prefixed_root_as_text_history_node_unchecked(buf: &[u8]) -> TextHistoryNode {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<TextHistoryNode>(buf) }
}
#[inline]
pub fn finish_text_history_node_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<TextHistoryNode<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_text_history_node_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<TextHistoryNode<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
