// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum TextModificationOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TextModification<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TextModification<'a> {
  type Inner = TextModification<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TextModification<'a> {
  pub const VT_TYPE_: flatbuffers::VOffsetT = 4;
  pub const VT_RANGE: flatbuffers::VOffsetT = 6;
  pub const VT_TEXT: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TextModification { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TextModificationArgs<'args>
  ) -> flatbuffers::WIPOffset<TextModification<'bldr>> {
    let mut builder = TextModificationBuilder::new(_fbb);
    if let Some(x) = args.text { builder.add_text(x); }
    if let Some(x) = args.range { builder.add_range(x); }
    builder.add_type_(args.type_);
    builder.finish()
  }


  #[inline]
  pub fn type_(&self) -> TextType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<TextType>(TextModification::VT_TYPE_, Some(TextType::PositiveText)).unwrap()}
  }
  #[inline]
  pub fn range(&self) -> Option<&'a TextRange> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<TextRange>(TextModification::VT_RANGE, None)}
  }
  #[inline]
  pub fn text(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TextModification::VT_TEXT, None)}
  }
}

impl flatbuffers::Verifiable for TextModification<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<TextType>("type_", Self::VT_TYPE_, false)?
     .visit_field::<TextRange>("range", Self::VT_RANGE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("text", Self::VT_TEXT, false)?
     .finish();
    Ok(())
  }
}
pub struct TextModificationArgs<'a> {
    pub type_: TextType,
    pub range: Option<&'a TextRange>,
    pub text: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for TextModificationArgs<'a> {
  #[inline]
  fn default() -> Self {
    TextModificationArgs {
      type_: TextType::PositiveText,
      range: None,
      text: None,
    }
  }
}

pub struct TextModificationBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TextModificationBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_type_(&mut self, type_: TextType) {
    self.fbb_.push_slot::<TextType>(TextModification::VT_TYPE_, type_, TextType::PositiveText);
  }
  #[inline]
  pub fn add_range(&mut self, range: &TextRange) {
    self.fbb_.push_slot_always::<&TextRange>(TextModification::VT_RANGE, range);
  }
  #[inline]
  pub fn add_text(&mut self, text: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TextModification::VT_TEXT, text);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TextModificationBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TextModificationBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TextModification<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TextModification<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TextModification");
      ds.field("type_", &self.type_());
      ds.field("range", &self.range());
      ds.field("text", &self.text());
      ds.finish()
  }
}
